name: Test_tag
on:
  workflow_dispatch:
  create:
    tags:
      - v*
  push:
	  
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  "finish workflow"